version: '3'
services:
  localstack:
    image: 'localstack/localstack'
    ports:
      - '4567-4584:4567-4584'
      - '8080:8080'
    environment:
      - DEFAULT_REGION=eu-central-1
      - DEBUG=0
      - SERVICES=dynamodb,s3
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ~/.aws:/root/.aws
      - /app/node_modules
      - /app/tmp
      - ./backend:/app
      - ./wait-for.sh:/opt/wait-for.sh
    ports:
      - '4000:4000'  
    depends_on:
      - 'localstack'
    command: ['/opt/wait-for.sh', 'localstack:4569', 'npm', 'run', 'offline']
    entrypoint: ['/bin/sh']
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
